project:
  type: website

website:
  title: "Documentation projet cartiflette ðŸ§€"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        menu:
          - text: Le projet sur Github
            url:  https://github.com/inseefrlab/cartiflette

format:
  html:
    theme:
      light: [minty, styles.scss]
      dark: sketchy
    css: styles.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 2000px
      margin-width: 0px
      gutter-width: 0.5rem


output: false